"""Export decrypted .env variables into the current shell environment or a file."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

from envault.vault import unlock


class ExportError(Exception):
    """Raised when export fails."""


def _parse_env_lines(text: str) -> dict[str, str]:
    """Parse KEY=VALUE lines, ignoring comments and blank lines."""
    result: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            result[key] = value
    return result


def export_to_env(
    enc_path: Path,
    passphrase: str,
    *,
    overwrite: bool = False,
) -> dict[str, str]:
    """Decrypt *enc_path* and inject variables into ``os.environ``.

    Returns the dict of variables that were exported.
    Raises :class:`ExportError` if a key already exists and *overwrite* is False.
    """
    tmp = enc_path.with_suffix(".tmp_export.env")
    try:
        unlock(enc_path, passphrase, output_path=tmp)
        text = tmp.read_text(encoding="utf-8")
    finally:
        if tmp.exists():
            tmp.unlink()

    variables = _parse_env_lines(text)
    if not overwrite:
        conflicts = [k for k in variables if k in os.environ]
        if conflicts:
            raise ExportError(
                f"Keys already set in environment (use overwrite=True): {conflicts}"
            )

    for key, value in variables.items():
        os.environ[key] = value

    return variables


def export_to_shell_script(
    enc_path: Path,
    passphrase: str,
    output_path: Optional[Path] = None,
) -> Path:
    """Decrypt *enc_path* and write an ``export KEY=VALUE`` shell script.

    If *output_path* is omitted, writes alongside the encrypted file as
    ``<stem>.export.sh``.  Returns the path of the written script.
    """
    if output_path is None:
        output_path = enc_path.with_suffix(".export.sh")

    tmp = enc_path.with_suffix(".tmp_export2.env")
    try:
        unlock(enc_path, passphrase, output_path=tmp)
        text = tmp.read_text(encoding="utf-8")
    finally:
        if tmp.exists():
            tmp.unlink()

    variables = _parse_env_lines(text)
    lines = ["#!/usr/bin/env sh", "# Generated by envault export — do not commit", ""]
    for key, value in variables.items():
        escaped = value.replace('"', '\\"')
        lines.append(f'export {key}="{escaped}"')
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
